### ISSUE TITLE
No se puede usar el comando /Tpask

### ISSUE THREAD

**Issue by Lug1233** [SebastianSoftware/ReinosMC#1]
Usar el comando /tpask (jugador) 
You do not have access to that command.
Teletransporte al jugador seleccionado
![bug](https://user-images.githubusercontent.com/94877871/142956835-88499f7f-ff0f-46b2-8a55-730a2b999afd.PNG)

**Comment by Sebasorova** [comment]
el comando /tpask no existe, el commando correcto es /tpa <jugador>
